name: "ArgoCD Apps Action"
description: "Github Action to update ArgoCD Applications"
inputs:
  target_branch:
    description: "target branch"
    required: false
    default: "main"
  create_pr:
    description: "create a PR if there are new updates"
    required: false
    default: "true"
  apps_folder:
    description: "folder to look for the app of apps"
    required: false
    default: "apps/manifests"
runs:
  using: composite
  steps:
    - name: Download ArgoCD Apps Action Binary
      env:
        ACTION_VERSION: "v0.0.5"
      shell: bash
      run: |
        wget https://github.com/ironashram/argocd-apps-action/releases/download/${ACTION_VERSION}/argocd-apps-action-${ACTION_VERSION}-linux-amd64.tar.gz
        wget https://github.com/ironashram/argocd-apps-action/releases/download/${ACTION_VERSION}/argocd-apps-action-${ACTION_VERSION}-linux-amd64.tar.gz.md5
        echo "Verifying MD5 checksum"
        md5sum argocd-apps-action-${ACTION_VERSION}-linux-amd64.tar.gz > checksum
        grep $(cat argocd-apps-action-${ACTION_VERSION}-linux-amd64.tar.gz.md5) checksum
        if [ $? -eq 0 ]; then
          echo "Checksum verified"
          tar -xvf argocd-apps-action-${ACTION_VERSION}-linux-amd64.tar.gz
          chmod +x argocd-apps-action
          mv argocd-apps-action /usr/local/bin/argocd-apps-action
        else
          echo "Checksum verification failed"
          exit 1
        fi

    - name: Run Action
      env:
        INPUT_TARGET_BRANCH: ${{ inputs.target_branch }}
        INPUT_CREATE_PR: ${{ inputs.create_pr }}
        INPUT_APPS_FOLDER: ${{ inputs.apps_folder }}
      shell: bash
      run: |
        # Run the ArgoCD Apps Action
        argocd-apps-action
