name: "go: build binaries"

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]

    steps:

      - name: Check out
        uses: actions/checkout@v4

      - name: Create Release
        run: |
          gh release create -t "${{ github.ref_name }}" "${{ github.ref_name }}" --generate-notes

      - name: Go Release Binaries
        uses: wangyoucao577/go-release-action@v1.48
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          pre_command: export CGO_ENABLED=0
          project_path: src/cmd
